### ISSUE TITLE
make-attention-action

### ISSUE THREAD

**Issue by h-kamada** [jsk-ros-pkg/jsk_demos#1045]
make-attention-action関数が定義されていないというエラーが出ますが、どこで定義されていますか？
@furushchev 

https://github.com/jsk-ros-pkg/jsk_demos/blob/master/jsk_demo_common/euslisp/pr2-attention-move.l#L6-L30

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_demos/search?utf8=%E2%9C%93&q=make-attention-action

--
◉ Kei Okada

**Comment by furushchev** [comment]
どこでそのエラーが出るのでしょうか？

**Comment by h-kamada** [comment]
https://github.com/jsk-ros-pkg/jsk_demos/blob/master/detect_cans_in_fridge_201202/euslisp/main.l#L11-L19
です。
attention-observation.lで定義されているので、先にattention-observation.lを読み込めばエラーが出なくなりそうです。

**Comment by h-kamada** [comment]
#1046

**Comment by furushchev** [comment]
@h-kamada Thanks! If you dont have any other problem, please close.
