### ISSUE TITLE
jsk_2013_04_pr2_610のREADME.md を良くする

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_demos#1079]
https://github.com/jsk-ros-pkg/jsk_demos/tree/master/README.md の内容を
https://github.com/jsk-ros-pkg/jsk_demos/tree/master/jsk_2013_04_pr2_610
に移して，グラフの起動の仕方，使い方，画面，解説を追加しましょう　 > @furushchev

**Comment by k-okada** [comment]
@h-kamada くんもhttps://github.com/jsk-ros-pkg/jsk_demos/tree/master/detect_cans_in_fridge_201202 のREADME.mdを追加しましょう

**Comment by furushchev** [comment]
issueを分けました。問題なければこのコミットはcloseしてもよさそうです。
