### ISSUE TITLE
Why travis test for interactive_behaivor_201409 passes?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_demos#1100]
without the deb release of face_recognition?

do you have any idea?

I have a build problem in a package which depends on interective_behavior_201409 implicitly. 
see https://github.com/jsk-ros-pkg/jsk_smart_apps/issues/60#issuecomment-152045390

**Comment by wkentaro** [comment]
this is because of this line.
https://github.com/jsk-ros-pkg/jsk_demos/blob/master/interactive_behavior_201409/package.xml#L25

**Comment by wkentaro** [comment]
this will be fixed by https://github.com/jsk-ros-pkg/jsk_travis/pull/180

**Comment by k-okada** [comment]
removing https://github.com/fkanehiro/hrpsys-base/pull/854 may fix this
problem, (why we have both face_detection and faece_recognition )

having missing deb on build_depend may ignored by rosdep with "ignore
error" option, but find_package(face_detection) failed during catkin b,
if you did not use face_detection on build time, such as C source code
requires them, you can remove such package names from find_package

--
◉ Kei Okada

**Comment by wkentaro** [comment]
I don't know about why `interactive_behavior_201409` depends on `face_recognition`.
@furushchev may know about it.

**Comment by furushchev** [comment]
main.l in `interactive_behavior_201409` subscribes `face_recognition/FaceRecognitionAction`.

**Comment by furushchev** [comment]
Current progress:
- [ ] fix travis.sh: jsk-ros-pkg/jsk_travis#180 -> this causes test fail on `interactive_behavior_201409`
- [ ] test `USE_DEB=true` since `face_recognition` is not yet released
- [ ] apply new `.travis` to `jsk_demos` repo
- [ ] add `face_recognition` to `.travis.rosinstall`

**Comment by wkentaro** [comment]
done with https://github.com/jsk-ros-pkg/jsk_demos/pull/1104
