### ISSUE TITLE
detect_cans_in_fridge2012のREADMEをつくる

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_demos#1115]
splited from: #1079 

@h-kamada くんもhttps://github.com/jsk-ros-pkg/jsk_demos/tree/master/detect_cans_in_fridge_201202 のREADME.mdを追加しましょう

**Comment by k-okada** [comment]
ping

--
◉ Kei Okada

**Comment by h-kamada** [comment]
すみません追加します...！
