### ISSUE TITLE
[drc_task_common] conservative_detection.launchを立ち上げるとエラーがでる

### ISSUE THREAD

**Issue by mttamtam** [jsk-ros-pkg/jsk_demos#1215]
（間違えて途中で送ってしまいました)
JAXONのdoor-valveデモをしようとして、
roslaunch drc_task_common conservative_detection.launch
をあげると、
![image](https://cloud.githubusercontent.com/assets/9166022/24654002/04a9028a-1973-11e7-90b3-06c925335c51.png)
このエラーが４つでてきて、rvizの上で視点を動かせません。
![default](https://cloud.githubusercontent.com/assets/9166022/24654173/8e088578-1973-11e7-902d-4f477cd14dbe.png)

**Comment by mttamtam** [comment]
rviz_animated_view_controllerがなかっただけでした。
http://wiki.ros.org/rviz_animated_view_controller
ここにしたがって
`sudo apt-get install ros-indigo-rviz-animated-view-controller`
をしたら動きました。
![image](https://cloud.githubusercontent.com/assets/9166022/24654541/07860d8e-1975-11e7-847d-f133e75d12da.png)

ubuntuをアップデートしたばかりのフィールドPCだったので、入ってなかったみたいです。
デモの前は本当に動くのかきちんと確認しておかないとダメですね。。

**Comment by k-okada** [comment]
どこかのpackage.xmlのrun_dependsに入れておきましょう

--
◉ Kei Okada


2017年4月4日 20:27 JuntaroTamura <notifications@github.com>:
