### ISSUE TITLE
update jsk_2013_04_pr2_610/README.md for indigo 

### ISSUE THREAD

**Issue by Affonso-Gui** [jsk-ros-pkg/jsk_demos#1219]
and https://github.com/jsk-ros-pkg/jsk_demos/tree/master/detect_cans_in_fridge_201202 too

**Comment by k-okada** [comment]
@furushchev please send your door detection launch file to jsk_recognitoin

**Comment by k-okada** [comment]
@Affonso-Gui, @708yamaguchi  can you check if this program can find door handle by Fetch robot?

**Comment by Affonso-Gui** [comment]
The README seems fine to me. What was the original problem?
