### ISSUE TITLE
fetcheus cannot find on Kinetic

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_demos#1239]
https://github.com/jsk-ros-pkg/jsk_demos/blob/master/jsk_2017_10_semi/CMakeLists.txt#L11
https://github.com/jsk-ros-pkg/jsk_demos/blob/master/jsk_2017_10_semi/package.xml#L43

It should be written as `run_depend` and `ros-kinetic-jsk-fetcheus` is not released yet.
Temporary solution for build is remove `fetcheus` from `find_package` and change it to `run_depend`.

**Comment by k-okada** [comment]
because fetch is not released on kinetic.
please create pull request that removes pr2eus, fetcheus, jsk_maps from
find_package

--
◉ Kei Okada


2018-04-25 19:23 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by k-okada** [comment]
and compile all jsk_demos program might be difficult please consider using
'catkin bt'

--
◉ Kei Okada


2018-04-25 19:31 GMT+09:00 Kei Okada <notifications@github.com>:

**Comment by knorth55** [comment]
>because fetch is not released on kinetic. please create pull request that removes pr2eus, fetcheus, jsk_maps from find_package

 i will work on it.

**Comment by knorth55** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/issues/2273 is caused by this issue

**Comment by knorth55** [comment]
`pr2eus` is already released in as `ros-kinetic-jsk-pr2eus`, isn't it?
https://discourse.ros.org/t/new-packages-for-kinetic-2017-03-05/1430

**Comment by k-okada** [comment]
yes , but you do not need to include in find_pcakge

--
◉ Kei Okada


2018-04-25 20:31 GMT+09:00 Shingo Kitagawa <notifications@github.com>:
