### ISSUE TITLE
中国ゴマデモをjsk_demosに入れてて，スピーカ and/or 携帯から呼び出せるようにしましょう

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_demos#1256]

**Comment by takayuki5168** [comment]
スピーカからは呼び出せるようになっております．

**Comment by takayuki5168** [comment]
PRを出しています　https://github.com/jsk-ros-pkg/jsk_demos/pull/1257

**Comment by takayuki5168** [comment]
@k-okada 現状,スピーカから #1257 を呼び出して,いつもどおりディアボロデモができるようになっています.

**Comment by takayuki5168** [comment]
@k-okada こちら　https://github.com/jsk-ros-pkg/jsk_demos/pull/1257　がマージされたのでclosedにして良いかと思います．
