### ISSUE TITLE
Create branch request for pr2/develop

### ISSUE THREAD

**Issue by mqcmd196** [jsk-ros-pkg/jsk_demos#1396]
@k-okada 
Can I push https://github.com/knorth55/jsk_demos/tree/develop/pr2 to jsk-ros-pkg/jsk_demos ? I want to manage it here

**Comment by k-okada** [comment]
we do not want to manage both deveop/pr2 and [subway2023](https://github.com/mqcmd196/jsk_demos/tree/subway2023), so please create reasonable PRs from develop/pr2 and let's merge them.
