### ISSUE TITLE
git clone is heavy

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_demos#155]
it takes 22 minutes to clone
```
$ time git clone https://github.com/jsk-ros-pkg/jsk_demos.git
Cloning into 'jsk_demos'...
remote: Counting objects: 7667, done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 7667 (delta 13), reused 0 (delta 0)
Receiving objects: 100% (7667/7667), 50.30 MiB | 22 KiB/s, done.
Resolving deltas: 100% (5285/5285), done.

real	22m28.156s
user	0m6.976s
sys	0m2.651s
```

**Comment by k-okada** [comment]
ok, I'll cleanup old heavy files, do not send PR or commit until I say ok

**Comment by k-okada** [comment]
ok, it ok, 
here is what I did, and if you find any trouble, please let me know asap, I'll keep back under /tmp directory so if my laptop reboot, all of data is gone.
``` 
2010  java -jar ~/Downloads/bfg-1.12.1.jar --delete-files '*.{bag,pgm,jpg}' .
 2011  git reflog expire --expire=now --all && git gc --prune=now --aggressive
 2012  git push -f origin master 
```

**Comment by garaemon** [comment]
thanks!

✉︎ Ryohei Ueda




On Tue, Feb 10, 2015 at 2:56 AM -0800, "Kei Okada" <notifications@github.com> wrote:












ok, it ok, 

here is what I did, and if you find any trouble, please let me know asap, I'll keep back under /tmp directory so if my laptop reboot, all of data is gone.

2010  java -jar ~/Downloads/bfg-1.12.1.jar --delete-files '*.{bag,pgm,jpg}' .
 2011  git reflog expire --expire=now --all && git gc --prune=now --aggressive
 2012  git push -f origin master
