### ISSUE TITLE
drc_task_common/operator_station_main.launchがエラー無く立ち上がるようにする

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_demos#183]
@mmurooka @YuOhara 新規の環境でやると真っ赤になるので対応お願いします．

なにか特殊な設定などがある場合はREADMEとかに設定方法を書いておいてください

**Comment by mmurooka** [comment]
どのPCで何を打ったか再現方法を教えていただけますでしょうか，確認してみます．

**Comment by garaemon** [comment]
sagamiです。再現方法はサラからjsk.rosbuildでインストールして、.desktopを実行です

✉︎ Ryohei Ueda




On Fri, Feb 13, 2015 at 6:54 AM -0800, "Masaki Murooka" <notifications@github.com> wrote:












どのPCで何を打ったか再現方法を教えていただけますでしょうか，確認してみます．

**Comment by YuOhara** [comment]
はい。
#182 とかも、多分その一部が問題だったんですよね・・・
多分python のライブラリ(fysomなど)のinstallとかも必要な気がします。

**Comment by garaemon** [comment]
はい、その通りです。fysomはpipかな、だとしたらrosdistroにリクエストを出して、、、というステップがあるけどそこまでやってとは言わないので、何か特殊なことが必要かをまずリストアップしましょう。


✉︎ Ryohei Ueda




On Fri, Feb 13, 2015 at 7:14 AM -0800, "YuOhara" <notifications@github.com> wrote:












はい。

#182 とかも、多分その一部が問題だったんですよね・・・

多分python のライブラリ(fysomなど)のinstallとかも必要な気がします。

**Comment by mmurooka** [comment]
https://github.com/jsk-ros-pkg/jsk_demos/pull/184 https://github.com/jsk-ros-pkg/jsk_demos/pull/185 https://github.com/jsk-ros-pkg/jsk_demos/pull/186 で、インストール必要なパッケージの説明、エラーの原因の説明、細かいエラーをなくす修正をしました。

**Comment by k-okada** [comment]
> fysomはpipかな、だとしたらrosdistroにリクエストを出して、、、というステップがあるけどそこまでやってとは言わないので

僕はそこまでやろう，と言いたいところです．ものすごく簡単ですよ．
https://github.com/ros/rosdistro/pull/6993/files

--
◉ Kei Okada


2015-02-14 12:45 GMT+09:00 Masaki Murooka <notifications@github.com>:

**Comment by mmurooka** [comment]
そこまでやってみました． https://github.com/ros/rosdistro/pull/7262

**Comment by garaemon** [comment]
今日中に計算機を分けて動くようにしましょう。

第一ステップ
1. /tfと/joint_statesをremap
2. 別マシンでやる
  1. robot_state_publisherが動いていない問題 -> 植田

**Comment by garaemon** [comment]
できた @ sagami
