### ISSUE TITLE
rqt上のimage_view2が安定しない

### ISSUE THREAD

**Issue by YuOhara** [jsk-ros-pkg/jsk_demos#368]
OCSのVIEWERで，rqt上のimage_view2での画像上の操作でうまくいかないことがあります．

* クリックを離しても，離してないように表示される
* 全く四角形等が表示されてないのに，クリックすると次の状態に移動してしまう．

**Comment by garaemon** [comment]
* https://github.com/jsk-ros-pkg/jsk_visualization/pull/364
* https://github.com/jsk-ros-pkg/jsk_common/pull/844

この二つでだいぶよくなるはず

**Comment by mmurooka** [comment]
２日くらい使ってますが，これまでの問題はなくなった気がします．ありがとうございます

**Comment by mmurooka** [comment]
(ohara commented)
