### ISSUE TITLE
地面の点群を除去するノードでtfエラーが出る

### ISSUE THREAD

**Issue by mmurooka** [jsk-ros-pkg/jsk_demos#543]
@garaemon さん，急ぎではないちょっとしたことですが，
おそらく昨日追加していただいた地面の点群を除去するノードから
以下のtfエラーが1Hzくらいで出ますので対応いただけますでしょうか．
```
[ERROR] [1430372474.816249818]: Lookup would require extrapolation into the past.  Requested time 1430371262.783901000 but the earliest data is at time 1430372464.830713033, when looking up transform from frame [odom] to frame [ground]
```

**Comment by garaemon** [comment]
とりあえず無視しても大丈夫です。

2015年4月30日木曜日、Masaki Murooka<notifications@github.com>さんは書きました:

> @garaemon <https://github.com/garaemon> さん，急ぎではないちょっとしたことですが，
> おそらく昨日追加していただいた地面の点群を除去するノードから
> 以下のtfエラーが1Hzくらいで出ますので対応いただけますでしょうか．
>
> [ERROR] [1430372474.816249818]: Lookup would require extrapolation into the past.  Requested time 1430371262.783901000 but the earliest data is at time 1430372464.830713033, when looking up transform from frame [odom] to frame [ground]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_demos/issues/543>.
>


-- 
✉︎ from iPhone

**Comment by garaemon** [comment]
たぶん出なくなったと思います

**Comment by mmurooka** [comment]
出なくなりました．ありがとうございます．
