### ISSUE TITLE
リモートからeusのS式を送れるようにする

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_demos#565]
@furushchev できましたか?

**Comment by furushchev** [comment]
はい。jsk_robot/roseus_remoteにあります。まだ2台でテストはできてませんがローカルでは動いていて、launchもそれっぽいものを置いてあります。

⌘ Yuki Furuta




On Fri, May 1, 2015 at 10:13 PM -0700, "Ryohei Ueda" <notifications@github.com> wrote:












@furushchev できましたか?

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_robot/pull/310
これかな

**Comment by furushchev** [comment]
それです。お知らせするのが遅くてすみませんでした！

⌘ Yuki Furuta




On Fri, May 1, 2015 at 10:20 PM -0700, "Ryohei Ueda" <notifications@github.com> wrote:












jsk-ros-pkg/jsk_robot#310

これかな

**Comment by garaemon** [comment]
ありがとう、みてみます

**Comment by k-okada** [comment]
おっと，https://github.com/euslisp/jskeus/blob/master/irteus/irtutil.l#L127 のeus-serverとconnect-serverでできますね．rosメッセージ経由というのではないけど．

**Comment by garaemon** [comment]
UDP対応なものがほしいのでeus-server/connect-serverは基本的に使えません。

socketの部分をUDPにしてrosから独立なUDPバージョンにするという作戦もありますが、jsk_network_toolsを使ったほうが信頼性は高そうです。

**Comment by garaemon** [comment]
ただ、10kbpsにルールがゆるまったのでTCPも通じるんじゃないかという話はあります
