### ISSUE TITLE
gazeboで動作確認するとsilverhammerがtimeoutで死ぬ

### ISSUE THREAD

**Issue by mmurooka** [jsk-ros-pkg/jsk_demos#669]

**Comment by k-okada** [comment]
創造だけど両方のマシン(roscore)で時間をわわせて、あとuse_sum_timeも伝搬させないと行けないとか？

**Comment by garaemon** [comment]
どちらも同じマシンを使っています．

もしかしたら外部からshutdown requestがきて，timeoutになっているだけかも

**Comment by garaemon** [comment]
とおもったら一部transvmをmachineタグで指定しているのがダメかも

**Comment by garaemon** [comment]
と思いましたがきのせいでした

**Comment by garaemon** [comment]
https://github.com/ros/ros_comm/blame/indigo-devel/clients/rospy/src/rospy/impl/masterslave.py#L439

rospyがtimeoutを指定していますね

**Comment by k-okada** [comment]
roscoreが2つあって片方でuse_sim_timeで片方が違うとだめな気がします。あるいは両方のuse_sim_timeだと/clockを伝搬させないとだめじゃないかな。

こちらか他の人でも再現できることなら投げておいて現地の人は実機でしかできないことに注力できるといいですんr。

--
◉ Kei Okada

2015/05/14 13:15、Ryohei Ueda <notifications@github.com> のメッセージ:

**Comment by garaemon** [comment]
@mmurooka https://github.com/jsk-ros-pkg/jsk_common/pull/925 これで治ったはずです。



> こちらか他の人でも再現できることなら投げておいて現地の人は実機でしかできないことに注力できるといいですんr。
はい、もちろんそうしたいです

**Comment by mmurooka** [comment]
ありがとうございました。

実機はかなり人気者で使える時間が限られているので
プログラムをひと通り回して、タイポとかがないことを事前に確認しておくのに使おうと思います。
本番直前にプログラムを書き換えて、実機テストはできないまま本番みたいなときにも、
さらっとシミュレーション上で確認できたら安心です。
