### ISSUE TITLE
音源定位してその方向を向く

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_demos#77]
PR2のマイクを使って

さすがに現在の実装は適当すぎるので、もうちょっと良くする

というかHarkが何か出していそうな気もするが

**Comment by furushchev** [comment]
@garaemon How could you do this? Now pr2_hark does not work. Is there any PRs related with this issue?

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_demos/pull/34/files#diff-57656d6a7bf714c71d0a2ffc971c4963R106

https://github.com/jsk-ros-pkg/jsk_demos/pull/34/files#diff-57656d6a7bf714c71d0a2ffc971c4963R151

**Comment by k-okada** [comment]
https://github.com/euslisp/jskeus/pull/157 is updated since garaemon is writing interactive demo
