### ISSUE TITLE
DRC task 一気通貫手順

### ISSUE THREAD

**Issue by yuki-asano** [jsk-ros-pkg/jsk_demos#934]
- [ ]                : オペレータ

(フィールド) : フィールド

# 開始/復帰手順
- [ ] 室岡、黒岩がやる
- [ ] 並列してros_bridgeの確認, fcプログラムの確認をする
- [ ] 並列してocsプログラムの確認をする
- hrpsysの確認
   - [ ] 基板確認(5, 12, 24V入れる)
   - [ ] リレーon
   - [ ] キャリブジョイント
   - [ ] 黒岩プログラムの起動(以下全て一つのコマンドで終わるはず)
      - [ ] リレーoff
      - [ ] サーボon
      - [ ] サーボoff
      - [ ] リレーon
      - [ ] servo with reset pose -> 確認
      - [ ] abcをいれる
      - [ ] リムーブフォースオフセット
      - [ ] start-defaultを全部する(ST, impedance)
      - [ ] 地面にロボットを下ろして、stの確認
      - [ ] go-pos(0 0  0)
- ocsの確認
   - [ ] hcfからのgo-pos(0 0 0)
   - [ ] ocsからのgo-pos(0, 0, 0)
   - [ ] リセットマニプポーズ
   - [ ] ハンドキャリブ
   - (フィールド)ハンドキャリブの終了(ハンド開で終了)を確認
   - [ ] ハンド、閉じる->開くの動作確認
   - [ ] インピーダンス切る(手に触らないように)
   - [ ] リセットフォースオフセット(ハンド)
   - [ ] インピーダンス入れ直す
   - [ ] ocsから再度go-pos(0 0 0)
   - [ ] 再度リセットポーズ
   - [ ] 垣内さんのやつ
   - (フィールド)ロボットをつる
   - [ ] abc, st, impedanceを止める
- [ ] 熊谷、寺澤にチェンジ

# T-0からの話
# 運転
- 運転動作
   - [ ] ハンドルが指令値についていっているかを魚眼カメラやmultisenseなどで確認（そんなに変な操作はしないはずなので左に切っていたはずなのに突然回せなくて右に戻ったなどの状況を見つけたらオペレータに伝えてください）
   - [ ] もし指令値についていけなくなったらOver writeで指令値を上書きしてクランクを真下の位置まで戻し（0度）て再度Correct Handle Poseにより掴み直す
- ゴールしたら
   - [ ] Go to egressボタンを押してシンクする
   - [ ] この間にrvizを元に戻す（vehicleを消す。PointCloud戻す(0.05->0.01)、Laserをつける）
   - [ ] Go to egressボタンの赤色が消えたらRealボタンをOff（緑->赤）にする
   - [ ] CommunicationをOff（緑->赤）にする
   - [ ] 野田にチェンジ

# 降車
- [ ] 右足動く1
- [ ] 右足動く2
- [ ] 右足動く3
- [ ] 左足動く
- [ ] 左足外1
- [ ] 左足外2
- [ ] 左足外3
- [ ] 左足ちょっと下1
- [ ] 左足ちょっと下2
- [ ] ちょっと動くかもしれない
- [ ] 左手開く
- [ ] 左手外1
- [ ] 左手外2
- [ ] 左手外3
- [ ] 左手外4
- [ ] 右足あげる
- [ ] 右足外1
- [ ] 右足外2
- [ ] 右足外3
- [ ] 右足外4
- [ ] 両足つく
- [ ] 右手あげる
- [ ] 右手腰に
- [ ] 右手座面

###あやしい
腰を動かす
お尻をあげる1
お尻をあげる2
お尻をあげる3
####

- [ ] 右足インピーダンス
- [ ] かかと浮かせる
- [ ] 右足外へ1
- [ ] 右足外へ2
- [ ] 右足外へ3
- [ ] 右足地面へつく
- [ ] ほんのちょっと立つ
- [ ] もうちょっと立つ
- [ ] もうちょっと立つ
- [ ] ちょっと膝を伸ばす

####
もうちょっとあるはず
####

- [ ] 室岡にチェンジ

# ドア
- [ ] ビークル消す、lasercloudつける、pointclound(0.05->0.01) (運転でやり忘れていた場合)
- [ ] Fixed Frame -> odom_on_groundを確認
- [ ] ドアの位置を確認
- [ ] ドア前に進む
- [ ] ドアノブ確認（カメラ下げる）
- [ ] インピーダンス切る
- [ ] リセットフォースオフセット
- [ ] インピーダンス入れ直す -> デフォルトで入る
- [ ] ドア開け
- [ ] 後ろに下がる
- [ ] ドアスルーポーズ
- [ ] ドアの中央に移動
- [ ] ドアの途中まで進む
- [ ] ドアの最後まで通過する
- [ ] ドアから離れてリセットマニプポーズ

# バルブ
- [ ] バルブの正面に歩く
- [ ] インピーダンス切る
- [ ] リセットフォースオフセット
- [ ] インピーダンス入れ直す -> デフォルトで入る
- [ ] バルブの初期回転角の確認
- [ ] バルブ認識(二回する必要がある)
- [ ] **認識結果の確認(失敗->手動で合わせる)**
- [ ] バルブを回す(exec)
- [ ] バルブ終了後にバルブから多めに下がる
- [ ] go-posで移動
- [ ] 小原にチェンジ(go-pos中)

# ドリル
- [ ] ドリルの正面に移動
- [ ] インピーダンス切る
- [ ] リセットフォースオフセット
- [ ] インピーダンス入れ直す
- [ ] 首下げてドリル位置確認
- [ ] drill-grasp
- [ ] **ドリルマーカーの位置合わせ（奥行き、反転）**
- [ ] ドリルを持っていることを確認
- [ ] drill-watch
- [ ] **ドリルマーカーの位置合わせ（回転）**
- [ ] drill-button(ボタン押し)
- [ ] 壁の方を向く(go-pos 0 0 -90など)
- [ ] drill-wall(壁に穴をあける。jaxon大きめ、hrp2小さめ)
- [ ] **壁が平面出ていることを確認** -> 実行
- [ ] 穴が開いたか確認
- [ ] リセットマニプポーズを送る(下が先かも)
- [ ] 次の方向を向く(左方向)
- [ ] ドリルを捨てるモーション
- [ ] 室岡にチェンジ

# サプライズ
- [ ] サプライズの正面に移動
- [ ] 首を動かしてサプライズの位置を確認
- [ ] インピーダンス切る
- [ ] リセットフォースオフセット
- [ ] インピーダンス入れ直す
- [ ] 室岡に任せる
- [ ] 押す前にインピーダンスハード
- [ ] テラインに進む
- [ ] 植田さんにチェンジ(go-pos中)

# テライン
- ブロックの幅は39cm
- [ ] Fixed Frame -> Groundに変える
- [ ] グリッドを10cm刻みにする
- [ ] 黒岩rvizを横視点にする
- [ ] テラインのぎりぎりまで動く
- [ ] 下向く(look ground) -> 段差(奥高い)を歩く(execute the plan)
- [ ] 下向く -> 段差(左高い)を歩く
- [ ] 下向く -> 平らな面に歩く
- [ ] 一個右のブロックに移動(右に38cm). go-pos(0 -0.38 0).
- [ ] 下向く-> 段差(手前高い)を歩く
- [ ] 下向く -> 段差(右高い)を歩く
- [ ] 下向く -> 段差を降りる

# 階段
- 階段の高さ(一段目: x cm, 二段目: y cm, 三段目: z cm, 四段目: zz cm) 
- [ ] /ocs/communication/laser_cloudに変更
- [ ] StairMarkerをつける, Terrainを消す.
- [ ] 階段の目の前まで移動
- [ ] ドアスルーポーズ
- [ ] 微調整
- [ ] ゴーステアポーズ(かがむ姿勢)
- [ ] 階段がすねで隠れない程度まで前進
- [ ] 垣内さんの（アールビスなんちゃらが出たらオーケー） -> 登る(1)
- [ ] 垣内さんの -> 登る(2)
- [ ] 垣内さんの -> 登る(3)
- [ ] 垣内さんの -> 登る(4)
- [ ] 垣内さんの -> go-posでL字の先へ進む
- [ ] エンドステアポーズ

# バッテリ切れ
- [ ] ?Vになったら実行(腰12V系: 11.0V、PC12V系: 11.7V, 80V系: ?V(多分落ちない))
   - ダイオードで0.7V下がる
   - 腰12V系: https://github.com/jsk-ros-pkg/trans_system/issues/131#issuecomment-108693354
   - PC12V系: https://github.com/jsk-ros-pkg/trans_system/issues/131#issuecomment-106671183
- [ ] リセットマニプポーズ
- [ ] 後ろに下がる(障害物を避ける)
- [ ] Emargency Pose(4足モード)を送る

# 時間配分(目安)
運転(6分)
降車(5分)
移動(3分)
ドア(4分)
移動(１分)
バルブ(4分)
移動(１分)
ドリル(12分)
移動(１分)
サプライズ(6分)
移動(1分)
開始前微調整(3分)
テライン(6分)
移動(1分)
階段(3分)

計57分

降車に失敗した場合(10分ロス)何を諦めるか
ドリル(12分)かテライン(10分)、もしくはサプライズ(6分)

ドア、バルブ、階段はやる

IHMCのタイム(参考、24倍速)
運転2秒、48秒
降車17秒、408秒
ドア開始まで6秒、144秒
ドア4秒,96秒
ドリル前まで4秒、96秒
ドリル24秒、576秒
バルブ前まで6秒、144秒
バルブ9秒、216秒
サプライズ前まで6秒、144秒
サプライズ3秒、72秒
テライン前まで2秒、48秒
テライン前での微調整1秒、24秒
テライン10秒、240秒
階段前まで2秒、48秒
階段6秒、144秒

**Comment by eisoku9618** [comment]
![fuga](https://cloud.githubusercontent.com/assets/4509039/7977715/3644f6d8-0a42-11e5-9433-2b5b56f4f56d.jpg)

**Comment by yuki-asano** [comment]
唐沢君(他、フィールドの方々)

開始/再開時、バッテリ切れ時は、
今のところ、上のチェックリストの手順で確認を行っていく予定です。
印刷する予定ですが、確認よろしくお願いします。

**Comment by yuki-asano** [comment]
開始手順を、T-xにしたがって並び替えました。

# T-45 ～ T-20
- ロボットを自動車に載せて準備完了にする必要がある
## 開始準備
### フィールド
- hrpsysの確認
   - [ ] 基板確認(5, 12, 24V入れる)
   - [ ] リレーon
   - [ ] キャリブジョイント
   - [ ] リレーoff
   - [ ] サーボon
   - [ ] サーボoff
   - [ ] リレーon
   - [ ] servo with reset pose
   - [ ] リセットポーズの確認
   - [ ] abcをいれる
   - [ ] リムーブフォースオフセット
   - [ ] start-defaultを全部する(ST, impedance)
   - [ ] 空中go-pos
   - [ ] 地面にロボットを下ろす
   - [ ] ロボットを揺すって確認(st)
   - [ ] ロボットを吊る
   - [ ] abc, ST, impedanceを切る
   - [ ] 運転時の姿勢を送る
   - [ ] 運転時の姿勢になったら練習通りに車に乗せる

## オペレータ
- [ ] ros_bridgeの確認, fcプログラムの確認をする
- [ ] ocsプログラムの確認をする
- [ ] Egress用の野田GUIをあげる
- ocsの確認
   - [ ] hcfからのgo-pos(0 0 0)
   - [ ] ocsからのgo-pos(0, 0, 0)
   - [ ] リセットマニプポーズ
   - [ ] ハンドキャリブ
   - (fi)ハンドキャリブの終了(ハンド開閉)を確認
   - [ ] ハンド開閉動作確認
   - [ ] インピーダンス切る(手に触らないように)
   - [ ] リセットフォースオフセット(ハンド)
   - [ ] インピーダンス入れ直す
   - [ ] ocsから再度go-pos(0 0 0)
   - [ ] 再度リセットポーズ
   - [ ] 垣内さんのやつ
 - [ ] 熊谷、寺澤にチェンジ

# T-20 ～ T-5
### 運転準備
- 無線通信開始(unlimited)
    - [ ] joyを読めているかどうか確認する（USB挿しなおしてvehicleのところを立ち上げ直し）
   - [ ] ストップインピーダンス
   - [ ] reset force offset
   - [ ] rqt_reconfigureでmultisenseおよびprosilicaのexposureなどを調節をする
   - [ ] rvizの表示を運転用に変える(vehicleをつける、PointCloudを0.01->0.05、Laserを消す)
   - [ ] 左上１番目のCommunicationボタンをOn（赤->緑）にする
   - [ ] 左上２番目のRealボタンをOn（赤->緑）にする
- 運転用のテスト開始
   - [ ] 首を下に下げてマーカーを見る
   - [ ] もう一度multisenseのマーカーが見える程度にrqt_reconfigureを調節する->人の目でハンドル位置を確認
   - [ ] Correct Handle Poseボタンを押して、クランクを掴みにいく
   - [ ] neck, accel, handleモードをすべてoperationに切り替える
   - [ ] 左のジョイスティックでハンドルをゆっくり回してみてハンドルの様子を確認する（その際マーカーが動いていることも確認する）
   - (フィールド)アクセルの調整方法を係の人に説明する（【重要！！最新版FAQ参照】）
   - [ ] 右のジョイスティックで右足を動かして（RPMを参考にしながら）アクセルMAX(RPM2000くらい),MIN(ギリギリ踏まない位置)を調整する
   - (フィールド)右足を操作し始めたら、エンジンの回転数（RPM）の変化をオペレータに連絡する
   - (フィールド)もしアクセルを踏めていなかったら、さっとロボットを車に乗せ直して上記の操作をする

# T-5 - T2
- T-3で無線がlimitedに切り替わる
- [ ] バッテリに切り替える 
- [ ] ギアをhighに切り替える

# T-0
- 電話を切る
- 運転スタート

**Comment by eisoku9618** [comment]
フィールドメンバーへのメモ

以下を 10:45 - 11:10 でやる．時間には余裕があるはず．

1. @t-karasawa 5V/12Vを入れてJAXONガチャをする
1. @t-karasawa 24Vを入れる
1. @t-karasawa リレーを入れる
1. @fsugai simple_shmで80Vが来ているか確認してからキャリブをする
1. 一息ついて一旦落ち着く **キャリブを忘れるとサーボONでピーッと鳴って焦るので忘れずに**
1. @fsugai ノートPCで体内PCにsshする．``roscd jaxon_ros_bridge/scripts && ipython -i jaxon_hrpsys.py ""``
1. @t-karasawa リレーを落とす
1. @fsugai ``hcf.startDRCInitiSequence(servo=True)``でもろもろを確認し， @orikuma ポーズになっている
1. みんなで車に載せる
1. 一息ついて一旦落ち着く
1. @t-karasawa 時間が余っていたら右足微調整の量を考えとく

### もろもろ

yesが聞かれるタイミングで分けると以下

1. リレーが切れている状態でサーボON/OFFでエラーリセット
1. リレーを入れてサーボON with reset-pose ．終わった瞬間に AutoBalancerが入る
1. @t-karasawa ロボットの腰を掴んで抑えた状態で， @fsugai が y を押してremove-force-sensor-offset がされる．終わった瞬間に，STとICが入る
1. @t-karasawa がロボットを立たせるのを待ってから， @fsugai がgo-posする
   - ガガッとなったらリレーを落としてC-cして ``hcf.servoOff()``をしてやり直す
1. @t-karasawa がロボットを吊るのを待ってから， @fsugai がst / abc / ic を全部切る
1. @fsugai が熊谷さん初期姿勢を送る
