### ISSUE TITLE
PR1040が冷蔵庫デモを途中で失敗する

### ISSUE THREAD

**Issue by chiwunau** [jsk-ros-pkg/jsk_demos#992]
アメリカに行く前に既に出てきた現象ですが、
冷蔵庫を開けたあとに缶を取り出すところで手を伸ばす位置が大きくずれてしまい缶が取り出せない問題です。

キャリブレーションのあとに治るはずと思ったが治りませんでした。　点群を見たら確かに少しいずれていますが、それほどではないと思います。

手が開いたら詳しく調べる予定です。

**Comment by k-okada** [comment]
これは治ったかな

**Comment by h-kamada** [comment]
まだ治ってないと思います。
オウ君のアカウントで起きた現象とのことなので、applicationで起きるかをまずは試してみようと思います。

**Comment by chiwunau** [comment]
治りました。
やはり僕の環境に問題があることが判明しました。
jsk_common_msgsをまだ入れてなく、古いバージョンのpose_detection_msgsが使われているのが原因だと思います。
お騒がせしました
